### ISSUE TITLE
Does it work with AngularJS 1.2.x?

### ISSUE THREAD

**Issue by enrique-ibarra** [angular-ui/ui-validate#10]
I'm trying to use the library but for some reason I wasn't able to have it working on AngularJS 1.2.28. However trying with AngularJS >= 1.3 it does work just fine.

Does it requires AngularJS >= 1.3?

Test AngularJS 1.2.28: https://jsfiddle.net/eibar/agsac2ew/10/
Test AngularJS 1.3.17: https://jsfiddle.net/eibar/mjzfgkb5/2/

Thanks!

**Comment by PowerKiKi** [comment]
It [requires 1.3](https://github.com/angular-ui/ui-validate/blob/master/bower.json#L8)
