### ISSUE TITLE
Out of date npm versions

### ISSUE THREAD

**Issue by okhomenko** [angular-ui/ui-validate#11]
Could you please update version on NPM? Not it is 1.0.0.

**Comment by PowerKiKi** [comment]
@ProLoser it seems that something went wrong on the [last deploy attempt](https://travis-ci.org/angular-ui/ui-validate/builds/71709306#L442). Would you either add me as collaborator on npm, so I can publish with my key, or debug it yourself ?

**Comment by gitnik** [comment]
+1

**Comment by PowerKiKi** [comment]
re-ping @ProLoser could you please add me as collaborator on npmjs.com so I can fix this issue, please ?

**Comment by dasrick** [comment]
+1

**Comment by ProLoser** [comment]
@PowerKiKi I don't see ui-validate on npmjs at all

**Comment by ProLoser** [comment]
nvm. npmjs is stupid because they don't lowercase my username when signing in.

**Comment by ProLoser** [comment]
Sorry for not doing this sooner, just added you

**Comment by PowerKiKi** [comment]
Automatic release was restored and 1.2.1 is finally available via npm.
