### ISSUE TITLE
Feature Request: Using $watchCollection from ui-validate-watch-collection

### ISSUE THREAD

**Issue by blowsie** [angular-ui/ui-validate#12]
I used the `ui-validate-watch` directive on my element hoping that the source code would be smart enough to handle arrays. Sadly it didn't, not as I expected at least.

I dag into the source code here https://github.com/angular-ui/ui-validate/blob/master/src/validate.js#L139 and found that only each item in the array is being watched, and not the the array itself. 

I can only assume that the use case for this implementation was something along the lines of `ui-validate-watch="['someValueModel', 'someOtherValueModel']"`

My use case is actually watching an entire array, perhaps something along the lines of `ui-validate-watch-collection="'myArray'"` .

If this is something that could be added to ui-validate, I could try and create a PR.
If I am misusing the module, could you please explain how to achieve my goal?

**Comment by PowerKiKi** [comment]
This project does not have many active contributors at the time. So I am afraid that nobody could give you an answer. I guess the best is for you to thoroughly analyse the code and if if you still believe a PR is necessary, then I'll merge it (as long as it looks good).

**Comment by r0b-** [comment]
+1

As a work-around I ended up watching the array's length to trigger the ui-validate expression

```
ui-validate-watch="'myArray.length'"
```

**Comment by r0b-** [comment]
I made a pull request for that feature... https://github.com/angular-ui/ui-validate/pull/16

**Comment by PowerKiKi** [comment]
Closed via #16
