### ISSUE TITLE
demo in html preview

### ISSUE THREAD

**Issue by seafoam6** [angular-ui/ui-validate#14]
Forgive me if this isn't the best place to post this. 

The demo at the url linked from this page https://angular-ui.github.io/ (it links to an htmlpreview page [http://htmlpreview.github.io/?https://github.com/angular-ui/ui-validate/master/demo/index.html]) does not work. I'm not sure why. I cloned it to try to fix the issue, but the demo DOES work. Just not in that htmlpreview.github link. 

Having the demo seem broken will discourage people from using the module. Which I think is a disservice with how great the code is. Thanks!

**Comment by PowerKiKi** [comment]
It works for me when typing `john.doe@mail.com` in the first field. What doesn't work for you ?

**Comment by seafoam6** [comment]
I just tried this on my home computer. Same issue. 

I took a screen cap: https://imgur.com/WojKhJ1

here's the console errors: 

```
Mixed Content: The page at 'https://htmlpreview.github.io/?https://github.com/angular-ui/ui-validate/master/demo/index.html' was loaded over HTTPS, but requested an insecure script 'http://pagead2.googlesyndication.com/pagead/show_ads.js'. This request has been blocked; the content must be served over HTTPS.
htmlpreview.min.js:1 Mixed Content: The page at 'https://htmlpreview.github.io/?https://github.com/angular-ui/ui-validate/master/demo/index.html' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/angularjs/1.4.1/angular.js'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ htmlpreview.min.js:1
htmlpreview.min.js:1 Mixed Content: The page at 'https://htmlpreview.github.io/?https://github.com/angular-ui/ui-validate/master/demo/index.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ htmlpreview.min.js:1
htmlpreview.github.io/:1 Refused to execute script from 'https://raw.githubusercontent.com/angular-ui/ui-validate/master/dist/validate.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
htmlpreview.github.io/:2 Uncaught ReferenceError: angular is not defined
(program):40 Uncaught ReferenceError: angular is not defined
htmlpreview.github.io/:2 Uncaught ReferenceError: angular is not defined
```

**Comment by PowerKiKi** [comment]
The URL listed on http://angular-ui.github.io/ is non secure HTTP, but what you showed is HTTPS. That explains the difference. But it doesn't mean it's right. I'll change it to use HTTPS as much as possible.

Thanks for reporting.

**Comment by PowerKiKi** [comment]
Fixed in https://github.com/angular-ui/ui-validate/commit/0d7b9b04bf1dec8f3f7c7b94e3141c1d02331347
