### ISSUE TITLE
ui-validate makes model undefined

### ISSUE THREAD

**Issue by silentFred** [angular-ui/ui-validate#17]
ui-validate makes the model undefined after change for some reason. My college has the same issue in a completely different situation. any idea why this might happen?

**Comment by hrnw** [comment]
I have the same problem with a validation that works fine for several months. With Version 1.0.0 all works fine.

**Comment by PowerKiKi** [comment]
@hrnw could you pinpoint what exact commit introduced the bug ? There were several versions since 1.0.0

**Comment by silentFred** [comment]
@PowerKiKi i'm running with 1.2.0

**Comment by PowerKiKi** [comment]
Could you try every single commit between 1.0.0 and 1.2.0 to figure out when the problem was introduced ?

**Comment by hrnw** [comment]
In my case the commit #c77a5d4b97a8fae74f4645e2dc17323bc805060f is working and the commit #6ba458bedf5308c25f0e644c8fc6c234b432f569 doesn't work.
@silentFred can you confirm that?

**Comment by silentFred** [comment]
Goodness,  ill have to set out some time to test. What does the diff look
like between those two commits?

**Comment by PowerKiKi** [comment]
Should be fixed by #19
