### ISSUE TITLE
is there documentation anywhere? 

### ISSUE THREAD

**Issue by ganqqwerty** [angular-ui/ui-validate#22]
Seems to be a great library compared to the implementing the validators in ngModelController, but I don't see any documentation except this one: https://htmlpreview.github.io/?https://github.com/angular-ui/ui-validate/master/demo/index.html

**Comment by PowerKiKi** [comment]
There is nothing more than the demo that you found. If you feel that something should be added, either to the demo, or README, feel free to create a Pull Request

**Comment by ganqqwerty** [comment]
yeah, I think I figured this out and I'm able to come up with a little tutorial
